### ISSUE TITLE
install plugins via an additional etcdkey

### ISSUE THREAD

**Issue by cwolfes** [cloudogu/jenkins#47]
### Implement a mechanism similar to the one used in sonar dogu to install additional plugins.

etcdkey: `dogu/jenkins/plugins/default`
value: `"docker-plugin,docker-build-step,..."`

_we use groovy for parsing, therefore it would be easy to use a more complex json structure, but to be compliant with the sonar implementation we use a simple comma separated string._

**Comment by mbehlendorf** [comment]
resolved with #48
